language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: M/v3Z+5BVPl5p5k+oVAY62GyHNEpR3a6I935FKNwcJT+U8+Hjq4KZktBNPSTGz8sZ2w360LoXBEIMkqBu20sC6d6M2K6ephHUrzUw7rde4H0boygQ9parpOTDBhVCh8vpG+F8EyExARTZ+gGl2qc6SYOCmhAUqkZ5xNO/LOsHbM=
  - secure: Q8x0kP6u0LDg4/qDWKlJPpQ82uGCU1svfzL87zxduaQc81AC2m0chEYPHudWDa5usiJb3Rq3yISRphGJZMKA5RQUvSkz8Tq3/qjnkt0T0Uwb7o9LMDZEJExkVzGawDn9k4AbZHqtQee8JkyiURHOLlKA0A1jF10SlEs/XUozUq4=
script: node_modules/.bin/intern-runner config=tests/intern
